volumes:
  postgresql:
services:
  pg_db:
    image: postgres
    restart: always
    env_file:
      - ./bet_maker/.env
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
  line_provider:
    build: ./line_provider
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./line_provider/.env
    command: python ./src/main.py
  bet_maker:
    build: ./bet_maker
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - line_provider
      - pg_db
    env_file:
      - ./bet_maker/.env
    environment:
      - PROVIDER_HOST=line_provider
      - POSTGRES_HOST=pg_db
    command: python ./src/main.py